export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const MODIFY_USER_REQUEST = 'MODIFY_USER_REQUEST'
export const MODIFY_USER_SUCCESS = 'MODIFY_USER_SUCCESS'
export const MODIFY_USER_FAILURE = 'MODIFY_USER_FAILURE'

export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST'
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS'
export const GET_GROUPS_FAILURE = 'GET_GROUPS_FAILURE'

export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST'
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS'
export const GET_GROUP_FAILURE = 'GET_GROUP_FAILURE'

export const MODIFY_GROUP_REQUEST = 'MODIFY_GROUP_REQUEST'
export const MODIFY_GROUP_SUCCESS = 'MODIFY_GROUP_SUCCESS'
export const MODIFY_GROUP_FAILURE = 'MODIFY_GROUP_FAILURE'
